// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Du6aN2iMY-bG77bijJAac4QlyLS7BXA',
    appId: '1:446152477698:web:97c6d6cdba10969ab56b1b',
    messagingSenderId: '446152477698',
    projectId: 'german-for-u',
    authDomain: 'german-for-u.firebaseapp.com',
    storageBucket: 'german-for-u.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeHeXngJz-YYTZ6YfDbo7IeCPv7J8Npbc',
    appId: '1:446152477698:android:716f71dac85f2590b56b1b',
    messagingSenderId: '446152477698',
    projectId: 'german-for-u',
    storageBucket: 'german-for-u.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVvUqKHs83_PhisPg1712KtL_aeJXD5mk',
    appId: '1:446152477698:ios:7b67c4adadf31df5b56b1b',
    messagingSenderId: '446152477698',
    projectId: 'german-for-u',
    storageBucket: 'german-for-u.appspot.com',
    androidClientId: '446152477698-28fulo8r76g7svl8bla5ctpg2rbaj3ua.apps.googleusercontent.com',
    iosClientId: '446152477698-rhug4illvudcvj3nbrmnrlp2bv6t64g9.apps.googleusercontent.com',
    iosBundleId: 'hou.edu.vn.germanForU',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVvUqKHs83_PhisPg1712KtL_aeJXD5mk',
    appId: '1:446152477698:ios:d7e4dc1e62b1fd85b56b1b',
    messagingSenderId: '446152477698',
    projectId: 'german-for-u',
    storageBucket: 'german-for-u.appspot.com',
    androidClientId: '446152477698-28fulo8r76g7svl8bla5ctpg2rbaj3ua.apps.googleusercontent.com',
    iosClientId: '446152477698-7gupudl4l4jnih5f9k3buii7sgc69d66.apps.googleusercontent.com',
    iosBundleId: 'hou.edu.vn.germanForU.RunnerTests',
  );
}
